### PR TITLE
Feature: Add distinctWhen

### PR DESCRIPTION
**Pull request by felangel**
`distinctWhen` will allow developers to apply the `distinct` operator on a `Stream` conditionally.

### CODE REVIEW

**Comment by natebosch** [comment]
Can you describe your use case?

**Comment by felangel** [comment]
We want to be able to filter a stream of SearchEvents and ignore duplicate searches but allow duplicate RetryEvents.

**Comment by natebosch** [comment]
I wonder if it would be straightforward enough to use the built in `Stream.distict` and implement this with a custom equals check?

```dart
var distinctSearchOrRetry = events.distinct((previous, next) {
  // retry events are always considered distinct
  if (next is RetryEvent) return false;
  return previous == next;
});
```

compared with:

```dart
var distinctSearchOrRetry = events.transform(distinctWhen((e) => e is RetryEvent));
```

It's a little more verbose, but it might sidestep some of the questions around exactly what the meaning of `distinctWhen` is.

**Comment by felangel** [comment]
Sounds good, thanks for the feedback 👍

**Pull request closed without merging**
